apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: clv-backend
        ports:
        - containerPort: 8000
        env:
        - name: MODEL_PATH
          value: /app/artifacts/training/best_model.pth
        - name: SCALER_PATH
          value: /app/artifacts/training/scaler.joblib
